cocina_project/cocina_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('usuarios/', include('usuarios.urls')),
    path('', include('recetas.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cocina_project/recetas/urls.py
from django.urls import path
from . import views
from .views import delete_recipe

# Create your urls here

app_name = 'recetas'
urlpatterns = [
    path('new_recipe/',views.new_recipe,name='new_recipe'),
    path('',views.RecipesList.as_view(),name='home'),
    path('recetas/<int:pk>/<slug:slug>/',views.DetailedRecipe.as_view(),name='recipe_detail'),
    path('my_recipes/',views.MyRecipes.as_view(),name='my_recipes'),
    path('recipe/edit/<int:recipe_id>',views.edit_recipe,name='edit_recipe'),
    path('recetas/delete/<int:recipe_id>',delete_recipe, name='delete_recipe')

]

cocina_project/usuarios/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy

app_name = 'usuarios'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='usuarios/login.html',), name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='recetas:home'), name='logout'),
    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='usuarios/password_change.html',success_url=reverse_lazy('usuarios:password_change_done')), name='password_change'),    
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name='usuarios/password_change_done.html'), name='password_change_done'),
    path('password_reset/', auth_views.PasswordResetView.as_view(template_name='usuarios/password_reset.html'), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='usuarios/password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='usuarios/password_reset_confirm.html'), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='usuarios/password_reset_complete.html'), name='password_reset_complete'),
    path('profile/', views.profile, name='profile'),
    path('edit_profile/', views.edit_profile, name='edit_profile'),
]

cocina_project/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'styles.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <title>{% block title %} My site {% endblock %}</title>
</head>

<body>
    {% block content %}{% endblock %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>

</html>

cocina_project/templates/navbar.html
{% load static %}
<div class="container">
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container">
            <a class="navbar-brand" href="{% url 'recetas:home' %}">
                <img class="logo" src="{% static 'images/logos/cocina_para_todos_logo.png' %}" alt="Logo">
            </a>
        </div>
        <div class="container">
            <ul class="navbar-nav justify-content-end">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'usuarios:login' %}">Login</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'usuarios:signup' %}">Sign Up</a>
                </li>
            </ul>
        </div>
    </nav>
</div>

cocina_project/templates/navbar_profile.html
{% load static %}
<div class="container">
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container">
            <a class="navbar-brand" href="{% url 'recetas:home' %}">
                <img class="logo" src="{% static 'images/logos/cocina_para_todos_logo.png' %}" alt="Logo">
            </a>
        </div>
        <div class="container">
            <ul class="nav nav-tabs justify-content-end">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                        aria-expanded="false">
                        Profile
                    </a>
                    <ul class="dropdown-menu">
                        <li>
                            <a class="dropdown-item" href="{% url 'usuarios:profile' %}">My profile</a>
                        </li>
                        <li>
                            <hr class="dropdown-divider">
                        </li>
                        <li>
                            <a class="dropdown-item" href="{% url 'usuarios:password_change' %}">Change Password</a>
                        </li>
                        <li>
                            <hr class="dropdown-divider">
                        </li>
                        <li>
                            <a class="dropdown-item" href="{% url 'usuarios:edit_profile' %}">Edit Profile</a>
                        </li>
                    </ul>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                        aria-expanded="false">
                        Recipes
                    </a>
                    <ul class="dropdown-menu">
                        <li>
                            <a class="dropdown-item" href="{% url 'recetas:my_recipes' %}">My recipes</a>
                        </li>
                        <li>
                            <hr class="dropdown-divider">
                        </li>
                        <li>
                            <a class="dropdown-item" href="{% url 'recetas:new_recipe' %}">New Recipe</a>
                        </li>
                    </ul>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-danger" href="{% url 'usuarios:logout' %}">Logout</a>
                </li>
            </ul>
        </div>
    </nav>
</div>