cocina_project/cocina_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('usuarios/', include('usuarios.urls')),
    path('', include('recetas.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cocina_project/recetas/urls.py
from django.urls import path
from . import views
from .views import delete_recipe

# Create your urls here

app_name = 'recetas'
urlpatterns = [
    path('new_recipe/',views.new_recipe,name='new_recipe'),
    path('',views.RecipesList.as_view(),name='home'),
    path('recetas/<int:pk>/<slug:slug>/',views.DetailedRecipe.as_view(),name='recipe_detail'),
    path('my_recipes/',views.MyRecipes.as_view(),name='my_recipes'),
    path('recipe/edit/<int:recipe_id>',views.edit_recipe,name='edit_recipe'),
    path('recetas/delete/<int:recipe_id>',delete_recipe, name='delete_recipe')

]

cocina_project/recetas/models.py
from django.db import models
from categories.models import Category
from django.contrib.auth.models import User
from django.utils.text import slugify
from django.core.exceptions import ValidationError

# Create your models here.


class Recipe(models.Model):
    title = models.CharField(max_length=255)
    description = models.TextField()
    ingredients = models.TextField()
    steps = models.TextField()
    preparation_time = models.FloatField()
    image = models.ImageField(upload_to='recipe_images/')
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    slug = models.SlugField(default="", null=False)

    def __str__(self):
        return self.title
    
    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        if Recipe.objects.filter(title=self.title, author=self.author).exists():
            raise ValidationError('You have already published a recipe with this title.')
        super().save(*args, **kwargs)

    def average_rating(self):
        ratings = self.ratings.all()
        if ratings.exists():
            return sum(rating.score for rating in ratings) / ratings.count()
        return 0

    def rating_count(self):
        return self.ratings.count()

cocina_project/recetas/forms.py
from django import forms
from .models import Recipe

from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit, Layout, Field, Div

# Add your forms here

class RecipeForm(forms.ModelForm):
    class Meta:
        model = Recipe
        fields = ['title','description','ingredients','steps','preparation_time',
                    'image','category']
        
        def __init__(self, *args, **kwargs):
            super().__init__(*args, **kwargs)
            self.helper = FormHelper()
            self.helper.form_method = 'post'
            self.helper.form_class = 'form-floating mb-3'
            self.helper.layout = Layout(
            Div(
                Field('title', css_class='form-control', wrapper_class='form-floating mb-3', placeholder='Recipe Title'),
                css_class='form-floating mb-3'
            ),
            Div(
                Field('description', css_class='form-control', wrapper_class='form-floating mb-3', placeholder='Description'),
                css_class='form-floating mb-3'
            ),
            Div(
                Field('ingredients', css_class='form-control', wrapper_class='form-floating mb-3', placeholder='Ingredients'),
                css_class='form-floating mb-3'
            ),
            Div(
                Field('steps', css_class='form-control', wrapper_class='form-floating mb-3', placeholder='Steps'),
                css_class='form-floating mb-3'
            ),
            Div(
                Field('preparation_time', css_class='form-control', wrapper_class='form-floating mb-3', placeholder='Preparation Time'),
                css_class='form-floating mb-3'
            ),
            Div(
                Field('image', css_class='form-control-file', wrapper_class='form-floating mb-3'),
                css_class='form-floating mb-3'
            ),
            Div(
                Field('category', css_class='form-control', wrapper_class='form-floating mb-3', placeholder='Category'),
                css_class='form-floating mb-3'
            ),
            Submit('submit', 'Save Recipe', css_class='btn btn-primary')
            )

class RecipeSearchForm(forms.Form):
    query = forms.CharField(label='',max_length=100,required=False)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_method = 'get'
        self.helper.form_class = 'd-flex'
        self.helper.layout = Layout(
            Field('query', css_class='form-control me-2', placeholder='Search'),
            Submit('search', 'Search', css_class='btn btn-primary mb-2')
        )

cocina_project/recetas/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.views import generic
from .forms import RecipeForm, RecipeSearchForm
from .models import Recipe
from django.contrib.auth.mixins import LoginRequiredMixin
from django.utils.text import slugify
from django.http import HttpResponseForbidden
from comments.forms import CommentForm
from comments.models import Comment
from django.urls import reverse
from django.views.generic.edit import FormMixin
from valoraciones.forms import RatingForm
from valoraciones.models import Rating
# Create your views here.

class RecipesList(generic.ListView):
    model = Recipe
    paginate_by = 3
    context_object_name = "recipes_list"
    template_name = "recetas/recipes.html"
    def get_queryset(self):
        queryset = Recipe.objects.order_by("-updated_at")
        query = self.request.GET.get('query')
        if query:
            queryset = queryset.filter(title__icontains=query)
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['search_form'] = RecipeSearchForm(self.request.GET)
        return context
    
    
class DetailedRecipe(FormMixin,generic.DetailView):
    model = Recipe
    context_object_name = "detailed_recipe"
    template_name = "recetas/detailed_recipe.html"
    form_class = CommentForm

    def get_success_url(self):
        return reverse('recetas:recipe_detail', kwargs={'pk': self.object.pk, 'slug': self.object.slug})

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['comments'] = Comment.objects.filter(recipe=self.object)
        context['ratings'] = Rating.objects.filter(recipe=self.object)
        context['average_rating'] = self.object.average_rating()
        context['rating_count'] = self.object.rating_count()

        if self.request.user.is_authenticated:
            context['comment_form'] = self.get_form()
            context['rating_form'] = RatingForm()
        else:
            context['comment_form'] = None
            context['rating_form'] = None
        return context

    def post(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return redirect('usuarios:login')  # Redirect to login page if not authenticated
        self.object = self.get_object()
        
        if 'comment_submit' in request.POST:
            comment_form = self.get_form()
            if comment_form.is_valid():
                return self.form_valid(comment_form)
            else:
                return self.form_invalid(comment_form)
        elif 'rating_submit' in request.POST:
            rating_form = RatingForm(request.POST)
            if rating_form.is_valid():
                new_rating = rating_form.save(commit=False)
                new_rating.recipe = self.object
                new_rating.user = self.request.user
                new_rating.save()
                return redirect(self.get_success_url())
            else:
                return self.form_invalid(rating_form)

    def form_valid(self, form):
        new_comment = form.save(commit=False)
        new_comment.recipe = self.object
        new_comment.user = self.request.user
        new_comment.save()
        return super().form_valid(form)

@login_required
def new_recipe(request):
    if request.method == 'POST':
        form = RecipeForm(request.POST, request.FILES)
        if form.is_valid():
            recipe = form.save(commit=False)
            recipe.author = request.user
            recipe.save()
            return redirect('usuarios:profile')
    else:
        form = RecipeForm()
    return render(request,'recetas/create_recipe.html',{'form':form})


class MyRecipes(LoginRequiredMixin,generic.ListView):
    model = Recipe
    paginate_by = 3
    context_object_name = "recipes_list"
    template_name = "recetas/recipes.html"
    # def get_queryset(self):
    #     return Recipe.objects.filter(author=self.request.user).order_by("-updated_at")
    
    def get_queryset(self):
        queryset = Recipe.objects.filter(author=self.request.user).order_by("-updated_at")
        query = self.request.GET.get('query')
        if query:
            queryset = queryset.filter(title__icontains=query)
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['search_form'] = RecipeSearchForm(self.request.GET)
        return context
    
@login_required
def edit_recipe(request, recipe_id):
    recipe = get_object_or_404(Recipe, id=recipe_id)
    if request.method == 'POST':
        form = RecipeForm(request.POST, request.FILES, instance=recipe)
        if form.is_valid():
            recipe = form.save(commit=False)
            if recipe.title != Recipe.objects.get(pk=recipe.pk).title:
                recipe.slug = slugify(recipe.title)
            recipe.save()
            return redirect('usuarios:profile')
    else:
        form = RecipeForm(instance=recipe)
    return render(request, 'recetas/create_recipe.html', {'form': form})

@login_required
def delete_recipe(request,recipe_id):
    recipe = get_object_or_404(Recipe,id=recipe_id)
    if recipe.author != request.user:
        return HttpResponseForbidden("You are not allowed to delete this recipe.")
    
    recipe.delete()
    return redirect('usuarios:profile')
    

cocina_project/recetas/templates/recetas/create_recipe.html
{% extends 'base.html' %}
{% block title %}Create recipe{% endblock %}
{% load crispy_forms_tags %}
{% block content %}
{% include 'navbar_profile.html' %}
<div class="container">

    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form|crispy }}
        <div class="col-12">
            <button type="submit" class="btn btn-primary">Submit</button>
        </div>
    </form>

    <!-- <form class="row g-3">
        <div class="col-md-6">
            <label for="inputEmail4" class="form-label">Email</label>
            <input type="email" class="form-control" id="inputEmail4">
        </div>
        <div class="col-md-6">
            <label for="inputPassword4" class="form-label">Password</label>
            <input type="password" class="form-control" id="inputPassword4">
        </div>
        <div class="col-12">
            <label for="inputAddress" class="form-label">Address</label>
            <input type="text" class="form-control" id="inputAddress" placeholder="1234 Main St">
        </div>
        <div class="col-12">
            <label for="inputAddress2" class="form-label">Address 2</label>
            <input type="text" class="form-control" id="inputAddress2" placeholder="Apartment, studio, or floor">
        </div>
        <div class="col-md-6">
            <label for="inputCity" class="form-label">City</label>
            <input type="text" class="form-control" id="inputCity">
        </div>
        <div class="col-md-4">
            <label for="inputState" class="form-label">State</label>
            <select id="inputState" class="form-select">
                <option selected>Choose...</option>
                <option>...</option>
            </select>
        </div>
        <div class="col-md-2">
            <label for="inputZip" class="form-label">Zip</label>
            <input type="text" class="form-control" id="inputZip">
        </div>
        <div class="col-12">
            <div class="form-check">
                <input class="form-check-input" type="checkbox" id="gridCheck">
                <label class="form-check-label" for="gridCheck">
                    Check me out
                </label>
            </div>
        </div>
        <div class="col-12">
            <button type="submit" class="btn btn-primary">Sign in</button>
        </div>
    </form> -->
</div>
{% endblock %}

cocina_project/recetas/templates/recetas/detailed_recipe.html
{% extends 'base.html' %}
{% block title %}{{ detailed_recipe.title }}{% endblock %}
{% block content %}

{% if user.is_authenticated %}
{% include 'navbar_profile.html' %}
{% else %}
{% include 'navbar.html' %}
{% endif %}
<div class="container">

    <h1 class="h1 text-center text-danger mb-3">{{ detailed_recipe.title }}</h1>
    <div class="container">
        <div class="row mb-5">
            <img class="col-3" src="{{ detailed_recipe.image.url }}" alt="{{ detailed_recipe.slug }}"
                style="size-adjust: 100%;">
            <p class="col-9 fs-5">{{ detailed_recipe.description }}</p>
        </div>
        <div class="row mb-3">
            <h2 class="h2 text-center text-danger col-4">Author</h2>
            <h2 class="h2 text-center text-danger col-4">Preparation time</h2>
            <h2 class="h2 text-center text-danger col-4">Category</h2>
        </div>
        <div class="row mb-3">
            <p class="text-center fs-3 col-4">{{ detailed_recipe.author }}</p>
            <p class="text-center fs-3 col-4">{{ detailed_recipe.preparation_time }} horas</p>
            <p class="text-center fs-3 col-4">{{ detailed_recipe.category }}</p>
        </div>
        <div class="row mb-3">
            <h2 class="h2 text-start text-danger mb-3">Ingredients</h2>
            <p class="">{{ detailed_recipe.ingredients }}</p>
        </div>
        <div class="row mb-3">
            <h2 class="h2 text-start text-danger mb-3">Food preparation</h2>
            <p class="fs-6">{{ detailed_recipe.steps }}</p>
        </div>
        <h2>Average Rating: {{ average_rating }} ({{ rating_count }} ratings)</h2>
        <div class="row justify-content-evenly mb-3">
            {% if user.is_authenticated %}
            <a class="btn btn-primary col-4" href="{% url 'recetas:edit_recipe' detailed_recipe.id %}">Edit recipe</a>
            <form class="col-4" id="delete-form" action="{% url 'recetas:delete_recipe' detailed_recipe.id %}"
                method="POST" style="display: inline;">
                {% csrf_token %}
                <button type="button" class="btn btn-danger" onclick="confirmDelete()">Delete</button> 
            </form>

            <form method="post">
                {% csrf_token %}
                {{ rating_form.as_p }}
                <button type="submit" name="rating_submit">Rate</button>
            </form>
            {% else %}
            <br>
            {% endif %}
        </div>
    </div>
    <br>
    {% include 'comments/comments.html' %}

</div>
<script>
    function confirmDelete() {
        if (confirm("Are you sure you want to delete this recipe?")) {
            document.getElementById('delete-form').submit();
        }
    }
</script>
{% endblock %}

cocina_project/recetas/templates/recetas/recipes.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}Home{% endblock %}

{% block content %}
{% if user.is_authenticated %}
{% include 'navbar_profile.html' %}
{% else %}
{% include 'navbar.html' %}
{% endif %}

<div class="container">
    <div class="container">
        <form class="row d-flex mb-4 align-items-center" role="search" method="get">
            <div class="col-5">{{ search_form|crispy }}</div>
            <div class="col-3"><button class="btn btn-outline-success" type="submit">Search</button></div>
        </form>
    </div>
    {% if recipes_list %}
    {% for recipe in recipes_list %}
    <div class="container">
        <div class="row">
            <div class="col align-self-start">
                <h2 class="text-danger">
                    <a href="{% url 'recetas:recipe_detail' pk=recipe.id slug=recipe.slug %}">{{ recipe.title }}</a>
                </h2>
                <p class="lead">
                    {{ recipe.description|truncatewords:40 }}
                </p>
                <div>{{ recipe.author }} / {{ recipe.updated_at }}</div>
            </div>
            <div class="col">
                <div class="text-center"><img src="{{ recipe.image.url }}" alt="Profile Picture" mb-3" height="250px">
                </div>
            </div>
        </div>
    </div>
    <br>
    {% endfor %}
    <nav aria-label="Page navigation example">
        <ul class="pagination justify-content-center">
            {% if page_obj.has_previous %}
            <li class="page-item"><a class="page-link border border-danger text-danger"
                    href="?page={{ page_obj.previous_page_number }}">Previous</a></li>
            <li class="page-item"><a class="page-link border border-danger text-danger"
                    href="?page={{ page_obj.previous_page_number }}">{{ page_obj.previous_page_number}}</a></li>
            {% endif %}

            <li class="page-item"><a class="page-link border border-danger text-danger"
                    href="?page={{ page_obj.number }}">{{ page_obj.number}}</a></li>

            {% if page_obj.has_next %}
            <li class="page-item"><a class="page-link border border-danger text-danger"
                    href="?page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number}}</a></li>
            <li class="page-item"><a class="page-link border border-danger text-danger"
                    href="?page={{ page_obj.paginator.num_pages }}">...</a></li>
            <li class="page-item"><a class="page-link border border-danger text-danger"
                    href="?page={{ page_obj.next_page_number }}">Next</a></li>
            {% endif %}
        </ul>
    </nav>
    {% else %}
    <div>There are no posts yet</div>
    {% endif %}
</div>

{% endblock %}